import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        "primary-deep": "var(--primary-deep)",
        "primary-mild": "var(--primary-mild)",
        "primary-subtle": "var(--primary-subtle)",
        error: "var(--error)",
        "error-subtle": "var(--error-subtle)",
        success: "var(--success)",
        "success-subtle": "var(--success-subtle)",
        info: "var(--info)",
        "info-subtle": "var(--info-subtle)",
        warning: "var(--warning)",
        "warning-subtle": "var(--warning-subtle)",
        neutral: "var(--neutral)",
        "gray-50": "var(--gray-50)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "gray-950": "var(--gray-950)",
        surface: {
          base: "#F5F5F5",
          card: "#FFFFFF",
          sunken: "#FAFAFA",
        },
        border: {
          subtle: "#E5E5E5",
          strong: "#D4D4D4",
        },
        brand: {
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          300: "#93C5FD",
          400: "#60A5FA",
          500: "#2A85FF",
          600: "#0069F6",
          700: "#1E40AF",
          800: "#1E3A8A",
          900: "#0F2042",
          DEFAULT: "#2A85FF",
          hover: "#0069F6",
          light: "#2A85FF1A",
        },
        severity: {
          immediate: "#FF6A55",
          "immediate-bg": "#FF6A551A",
          "short-term": "#F59E0B",
          "short-term-bg": "#FFD40045",
          "medium-term": "#737373",
          "medium-term-bg": "#F5F5F5",
          safe: "#10B981",
          "safe-bg": "#05EB7624",
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
        ],
        heading: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
      },
      boxShadow: {
        card: "0 0.125rem 0.25rem rgba(0,0,0,0.06)",
        raised: "0 4px 12px rgba(0,0,0,0.08)",
        dropdown: "0 6px 16px rgba(0,0,0,0.10)",
        modal: "0 16px 40px -8px rgba(0,0,0,0.25)",
      },
      borderRadius: {
        card: "1rem", // rounded-2xl from template
        control: "0.75rem", // rounded-xl
      },
    },
  },
  plugins: [],
};
export default config;
